rootLogger.level = info
rootLogger.appenderRef.console.ref = console

appender.console.type = Console
appender.console.name = console
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{ISO8601} %-5p %c{1}: %m%n

logger.jetty.name = org.sparkproject.jetty
logger.jetty.level = warn
logger.parquet.name = org.apache.parquet
logger.parquet.level = warn
