spark.plugins=org.apache.spark.CometPlugin
spark.shuffle.manager=org.apache.spark.sql.comet.execution.shuffle.CometShuffleManager
spark.comet.enabled=true
spark.comet.exec.enabled=true
spark.comet.nativeLoadRequired=true
spark.comet.shuffle.enabled=true
spark.comet.exec.memoryPool=fair_unified
spark.comet.exec.memoryPool.fraction=0.90
spark.comet.exec.strictFloatingPoint=true
spark.comet.scan.icebergNative.enabled=true
spark.comet.explain.fallback.enabled=true
spark.comet.explain.format=verbose
spark.comet.parquet.write.enabled=false
spark.comet.metrics.enabled=false

